# secrets role tasks
- name: Copier les fichiers JSON dans rocketweb/secrets
  copy:
    src: "{{ playbook_dir }}/secrets/"
    dest: "./rocketweb/secrets/"
    mode: 0774

- name: Trouver les fichiers JSON dans le dossier rocketweb/secrets
  find:
    paths: "./rocketweb/secrets/"
    patterns: "*.json"
    recurse: no
    file_type: file
  register: json_files

- name: Afficher les fichiers de secrets trouvés
  debug:
    var: json_files.files

- name: Lire les fichiers JSON et créer les secrets Docker
  block:
    - name: Lire le fichier JSON
      slurp:
        src: "{{ item.path }}"
      register: json_content
      loop: "{{ json_files.files }}"
      loop_control:
        loop_var: item

    - name: Convertir le contenu JSON
      set_fact:
        json_data: "{{ json_content['results'] | map(attribute='content') | map('b64decode') | map('from_json') | list }}"

    - name: Créer les secrets Docker
      docker_secret:
        name: "{{ item.name }}"
        data: "{{ item.data }}"
        state: present
      loop: "{{ json_data | flatten | map(attribute='secrets') | flatten }}"

- name: Supprimer le répertoire secrets après la création des secrets Docker
  file:
    path: ./rocketweb/secrets
    state: absent
