- name: Initial Setup
  hosts: initial_group
  gather_facts: yes
  become: yes
  remote_user: root

  vars_files:
    - secrets.yml

  vars:

    ssh_key_path: "{{ PRIVATE_KEY }}.pub"
    ansible_user: "root"
    ansible_ssh_pass: "{{ ROOT_PASSWORD }}"

  roles:
    - update
    - packages
    - user
    - zsh
    - security
