---
- name: Installer Zsh
  apt:
    name: zsh
    state: present
  become: true

- name: Installer les dépendances pour Oh My Zsh
  apt:
    name:
      - git
      - curl
      - wget
      - unzip
      - fd-find
      - bat
      - jq
    state: present
  become: true

- name: Cloner le dépôt Oh My Zsh dans /etc/skel
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: /etc/skel/.oh-my-zsh
    depth: 1
  become: true

- name: Installer les plugins externes Oh My Zsh dans /etc/skel
  git:
    repo: "{{ item.repo }}"
    dest: "/etc/skel/.oh-my-zsh/custom/plugins/{{ item.name }}"
    depth: 1
  loop:
    - {
        name: "zsh-autosuggestions",
        repo: "https://github.com/zsh-users/zsh-autosuggestions",
      }
    - {
        name: "zsh-syntax-highlighting",
        repo: "https://github.com/zsh-users/zsh-syntax-highlighting",
      }
    - {
        name: "zsh-completions",
        repo: "https://github.com/zsh-users/zsh-completions",
      }
    - { name: "z", repo: "https://github.com/rupa/z" }
  become: true

- name: Créer un fichier .zshrc par défaut dans /etc/skel
  copy:
    dest: /etc/skel/.zshrc
    content: |
      # Oh My Zsh configuration
      export ZSH="/home/{{ ansible_user }}/.oh-my-zsh"
      ZSH_THEME="robbyrussell"
      plugins=(git sudo history extract command-not-found docker zsh-autosuggestions zsh-syntax-highlighting zsh-completions z)
      source $ZSH/oh-my-zsh.sh
  become: true

- name: Changer le shell par défaut à Zsh pour tous les utilisateurs
  shell: |
    for user in $(cut -d: -f1 /etc/passwd); do
      if [ -s $(which zsh) ]; then
        chsh -s $(which zsh) $user
      else
        echo "Zsh n'est pas installé pour $user"
      fi
    done
  become: true

- name: Appliquer la configuration Zsh aux utilisateurs existants
  block:
    - name: Copier .oh-my-zsh dans les répertoires utilisateurs
      synchronize:
        src: /etc/skel/.oh-my-zsh
        dest: /home/{{ item }}/.oh-my-zsh
      loop: "{{ ansible_users }}"
      become: true

    - name: Copier .zshrc dans les répertoires utilisateurs
      copy:
        src: /etc/skel/.zshrc
        dest: /home/{{ item }}/.zshrc
      loop: "{{ ansible_users }}"
      become: true
  when: ansible_users is defined and ansible_users | length > 0
