services:
  veloc:
    image: ghcr.io/gsoulat/veloc:latest
    container_name: veloc
    restart: unless-stopped
    networks:
      - rocketweb-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.veloc.entrypoints=web"
      - "traefik.http.routers.veloc.rule=Host(`veloc.berry.ovh`)"
      - "traefik.http.routers.veloc.middlewares=redirect-to-https@docker"
      - "traefik.http.routers.veloc-secure.entrypoints=websecure"
      - "traefik.http.routers.veloc-secure.rule=Host(`veloc.berry.ovh`)"
      - "traefik.http.routers.veloc-secure.tls=true"
      - "traefik.http.routers.veloc-secure.tls.certresolver=letsencrypt"
      - "traefik.http.services.veloc.loadbalancer.server.port=5000"
      # Ajout de la définition du middleware de redirection
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"

networks:
  rocketweb-network:
    external: true
