name: Deploy with Ansible

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Create secrets.yml
        run: |
          cat > secrets.yml << EOF
          SERVER_IP: ${{ secrets.SERVER_IP }}
          DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          CLOUD_INIT_SSHD_CONFIG_PATH: ${{ secrets.CLOUD_INIT_SSHD_CONFIG_PATH }}
          SSHD_CONFIG_PATH: ${{ secrets.SSHD_CONFIG_PATH }}
          SSH_KEY_TYPES: ${{ secrets.SSH_KEY_TYPES }}
          PRIVATE_KEY: "~/.ssh/private_key"
          EOF

      - name: Create host.ini
        run: |
          cat > host.ini << EOF
          [deploy_group]
          target ansible_host=${{ secrets.SERVER_IP }} ansible_user=${{ secrets.USERNAME }} ansible_ssh_private_key_file=~/.ssh/private_key
          EOF

      - name: Create SSH directory
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

      - name: Configure SSH
        run: |
          cat > ~/.ssh/config << EOF
          Host *
            StrictHostKeyChecking no
            UserKnownHostsFile=/dev/null
            ServerAliveInterval 60
            ServerAliveCountMax 30
            ConnectTimeout 180
          EOF
          chmod 600 ~/.ssh/config

      - name: Install SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/private_key
          chmod 600 ~/.ssh/private_key

      - name: Debug SSH key
        run: |
          ls -la ~/.ssh/private_key
          echo "SSH key content (first line):"
          head -n 1 ~/.ssh/private_key

      - name: Network Debug
        run: |
          echo "Testing basic connectivity..."
          ping -c 4 ${{ secrets.SERVER_IP }}

          echo "Testing port 22..."
          nc -zv ${{ secrets.SERVER_IP }} 22

          echo "Checking route..."
          traceroute ${{ secrets.SERVER_IP }}

      - name: SSH Debug
        run: |
          echo "SSH debug output..."
          ssh -vvv -i ~/.ssh/private_key ${{ secrets.USERNAME }}@${{ secrets.SERVER_IP }} 'echo test'

      - name: Add host key
        run: |
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
          cat ~/.ssh/known_hosts

      - name: Run Ansible playbook
        run: ansible-playbook -i host.ini deploy.yml -vv

      - name: Clean up sensitive files
        if: always()
        run: |
          rm -f ~/.ssh/private_key
          rm -f secrets.yml
          rm -f host.ini
